### ISSUE TITLE
BUG: Stripe still extending memberships when payment fails - see #5

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/pmpro-auto-renewal-checkbox#12]
Fix was applied here: https://github.com/LMNTL/pmpro-auto-renewal-checkbox/blob/stripe-extend/pmpro-auto-renewal-checkbox.php#L335-L341 but it looks like the conditionals might be mixed up

Forum thread (mods only):
https://www.paidmembershipspro.com/forums/topic/expiration-date-incorrect-after-failed-recurring-billing/

**Comment by ideadude** [comment]
I'm also seeing memberships extended for 30 days when users cancel through the cancel page too.
