### ISSUE TITLE
Stripe: Extended membership when payment fails

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/pmpro-auto-renewal-checkbox#5]
If a member's Subscription plan is deleted on stripe.com - typically due to 3 failed payment capture attempts for a subscription plan - the `` hook in this add-on will assign the user another payment period worth of membership. I.e. the membership enddate will be set to the end of the _next_ payment period (not the current one).

**Comment by ideadude** [comment]
Confirmed this issue is happening. Related to our expire instead of cancelling immediately code here: https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/blob/master/pmpro-auto-renewal-checkbox.php#L308-L426

**Comment by ideadude** [comment]
Fix is here. Also going to apply this to the pmpro_next_payment() method in the Stripe class in PMPro core. The delinquent property of Stripe customers is not well documents, so we might get surprised here, but this should fix the issue.

https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/commit/b4b93b0d0bd61c3fe885d191e74a5f11b5e4443e
